### ISSUE TITLE
Further explanation on need for ZephyrOS

### ISSUE THREAD

**Issue by truedat101** [jens6151/spresense-BLE-with-XIAO-BLE#1]
First of all, thank you for publishing this repository.  I actually like the sony sespresense camera, and want to build around it, but I really need to get it tethered to bluetooth for some remote control.  I was thinking XIAO fits figuratively, but had not yet done the analysis of pinouts or other issues related to the sony HAL and Ble library.

I was hoping to stick (1) stick with ArduinoBLE or NimBLE and (2) repeat the set up with a XIAO ESP32S3 or ESP32C3.   What I was missing from the problem / solution description was why one needs to move to the ZephyrOS https://github.com/jens-ajisai/spresense-BLE-with-XIAO-BLE#add-seedstudio-xiao-ble-support-to-zephyr-by-creating-board-definition-files .  Is this to get the Nordic UART?  

This isn't a bug report , rather a further request for explanation.   I will give this a try either way to understand the integration you have done.

**Comment by jens-ajisai** [comment]
The official nRF Connect SDK is based on ZephyrOS. What I am using is the official SDK provided by Nordic Semiconductor. The whole point is to create a BLE companion board compatible with the Bluetooth HCI H4 protocol (BLE Controller) because ArduinoBLE (BLE Host) is based on this protocol. - It is the standard protocol for BLE when the controller is on a dedicated chip.

If you can create a firmware for the ESP32 that is compatible with Bluetooth HCI H4 protocol (I would assume that is something available easily.), then you could use that too with ArduinoBLE. - You would go with the Espressif SDK and not with ZephyrOS.

I started the project with the goal of only using Arduino libraries. Therefore I chose this setup with ArduinoBLE.
An alternative option, which I would prefer nowadays, is to transfer the image to the board capable of BLE via serial communication (like UART) and write a dedicated application for Bluetooth there. That means having the whole Bluetooth stack (BLE Host + BLE Controller) on the BLE device and freeing up memory on the Spresense board. - It's an architectural decision and affects the overall complexity. My motivation would be mainly to remove ArduinoBLE, which at that time had some bugs and did not support privacy as I needed it. Maybe it improved now. The BLE Stack in nRF Connect SDK is excellent.

Please keep in mind that sending images by BLE is quite slow. It takes 10 to 30 seconds per image (depending on the size) after tuning the speed. I did that in the project jens-ajisai/kitchen-activity-detection-mlx90640-thingy91. There is also a Flutter app that receives the images and displays them on a phone. Maybe an inspiration?

If Wifi, which would be faster, is an option for you, then it would be more appropriate for the amount of data. - But as you see, I tried BLE too and it depends on your requirements. (Unfortunately, the iS110B add-on boards are not sold anymore. And if you try the ESP32 AT firmware without tweaking, it is really slow.)

**Comment by jens-ajisai** [comment]
And thanks for showing interest :)

**Comment by jens-ajisai** [comment]
One addition: I just noticed that I don't describe the feature to take camera images to send them to the phone by BLE. Hope it doesn't confuse you too much. It is completely on nRF Connect SDK for another board.

**Comment by truedat101** [comment]
Excellent response, thank you @jens-ajisai .  Excited to learn more about the approach.  I had some indication from talking to folks on the Seeed forum who "know", indicate the nRF Connect is the way to go.  I am now more convinced. 

On my end, I am also interested in the various methods for moving data from the Spresense over a network and either to another device for storage, or for some further processing.  I hope to publish a few designs around the Spresense for a wearable DIY camera or for use as a stationary capture device.  

I will run some experiments with your approach and hopefully have some further insights to report from my experience.

**Comment by truedat101** [comment]
What is a bit maddening about this iteration of IoT is there still isn't a straightforward non-proprietary phy sort of approach to fast data sync over non-WiFi infrastructure.  The old approach of beaming files was very cool.  Try sending files between an android and an iOS device...  

So I'll be settling on BLE or some wifi alternative like ESP-NOW.

**Comment by truedat101** [comment]
I think we can mark this as closed, as you have answered the rationale questions.
